package main

//Feat is astruct containing feat names Prerequisites and Effects
type Feat struct {
	FeatName     string
	Prerequisite string
	Effect       string
}

// Feats is a list of feats
type Feats struct {
	Actor                 Feat
	Alert                 Feat
	Athelete              Feat
	BarbedHide            Feat
	BountifulLuck         Feat
	BountifulLuck2        Feat
	Charger               Feat
	CritterFriend         Feat
	CrossbowExpert        Feat
	DefensiveDuelist      Feat
	DragonFear            Feat
	DragonFear2           Feat
	DragonHide            Feat
	DragonHide2           Feat
	DragonWings           Feat
	DrowHideMagic         Feat
	DrowHighMagic         Feat
	DualWielder           Feat
	DungeonDelver         Feat
	Durable               Feat
	DwarfResilience       Feat
	DwarvenFortitude      Feat
	ElelmentalAdept       Feat
	ElvenAccuracy         Feat
	ElvenAccuracy2        Feat
	EverbodysFriend       Feat
	FadeAway              Feat
	FadeAway2             Feat
	FeyTransportation     Feat
	FayTeleportation      Feat
	FlamesOfPhlegethos    Feat
	FlamesOfPhegethos2    Feat
	Grappler              Feat
	GreatWeaponMaster     Feat
	GrudgeBearer          Feat
	Healer                Feat
	HeavilyArmored        Feat
	HeavyArmorMaster      Feat
	HumanDetermination    Feat
	InfernalConstitution  Feat
	InfernalConstitution2 Feat
	InspiringLeader       Feat
	KeenMind              Feat
	LightlyArmored        Feat
	Linguist              Feat
	Lucky                 Feat
	MageSlayer            Feat
	MagicInitiate         Feat
	MartialAdept          Feat
	MediumArmorMaster     Feat
	Mobile                Feat
	ModeratelyArmored     Feat
	MountedCombat         Feat
	Observant             Feat
	OrcishFury            Feat
	OrcishFury2           Feat
	OrcishAggression      Feat
	PolarmMaster          Feat
	Prodigy               Feat
	Progidy2              Feat
	Resilient             Feat
	RitualCaster          Feat
	SavageAttacker        Feat
	SecondChance          Feat
	SecondChance2         Feat
	Sentinel              Feat
	Sharpshooter          Feat
	ShieldMaster          Feat
	Skilled               Feat
	Skulker               Feat
	SpellSniper           Feat
	SquatNimbleness       Feat
	SquatNimbleness2      Feat
	TavernBrawler         Feat
	Tough                 Feat
	WarCaster             Feat
	WeaponMaster          Feat
	WonderMaker           Feat
	WoodElfMagic          Feat
	WoodElfMagic2         Feat
}
