package main

type Spells struct {
AcidSplash Spell
ChillTouch Spell
DancingLights Spell
FireBolt Spell
Light Spell
MageHand Spell
Mending Spell
Message Spell
MinorIllusion Spell
PoisonSpray Spell
Prestigitation Spell
RayOfFrost Spell
ShockingGrasp Spell
TrueStrike Spell
Alarm Spell
BurningHands Spell
CharmPerson Spell
Colorspray Spell
ComprehendLanguages Spell
DetectMagic Spell
DisguiseSelf Spell
ExpeditiousRetreat Spell
FalseLife Spell
FeatherFall Spell
FindFamiliar spell
FloatingDisk spell
FogCloud spell
Grease spell
HideousLaughter Spell 
Identify Spell
IllusoryScript Spell 
Jump Spell
Longstrider Spell 
MageArmor Spell
MagicMissile Spell
ProtectionFromEvilAndGood Spell
Shield Spell
SilentImage Spell
Sleep Spell
Thunderwave Spell 
UnseenServant Spell
AcidArrow Spell Spell
AlterSelf  Spell
ArcaneLock  Spell
ArcanistsMagicAura  Spell
BlindnessDeafness  Spell
Blur  Spell
ContinualFlame  Spell
Darkness  Spell
Darkvision  Spell
DetectThoughts  Spell
EnlargeReduce  Spell
FlamingSphere  Spell
GentleRepose  Spell
GustOfWind  Spell
HoldPerson  Spell
Invisibility  Spell
Knock  Spell
Levitate  Spell
LocateObject  Spell
MagicMouth  Spell
MagicWeapon  Spell
MirrorImage  Spell
MistyStep  Spell
RayOfEnfeeblement  Spell
RopeTrick  Spell
ScorchingRay  Spell
SeeInvisibility  Spell
Shatter  Spell
SpiderClimb  Spell
Suggestion  Spell
Web Spell
AnimateDead  Spell
BestowCurse  Spell
Blink  Spell
Clairvoyance  Spell
Counterspell  Spell
DispelMagic  Spell
Fear  Spell
Fireball  Spell
Fly  Spell
GaseousForm  Spell
GlyphOfWarding  Spell
Haste  Spell
HypnoticPattern  Spell
LightningBolt  Spell
MagicCircle  Spell
MajorImage  Spell
Nondetection  Spell
PhantomSteed  Spell
ProtectionFromEnergy  Spell
RemoveCurse  Spell
Sending  Spell
SleetStorm  Spell
Slow  Spell
StinkingCloud  Spell
TinyHut  Spell
Tongues  Spell
VampiricTouch  Spell
WaterBreathing Spell
ArcaneEye  Spell
Banishment  Spell
BlackTentacles  Spell
Blight  Spell
Confusion  Spell
ConjureMinorElementals  Spell
ControlWater  Spell
DimensionDoor  Spell
Fabricate  Spell
FaithfulHound  Spell
FireShield  Spell
GreaterInvisibility  Spell
HallucinatoryTerrain  Spell
IceStorm  Spell
LocateCreature  Spell
PhantasmalKiller  Spell
Polymorph  Spell
PrivateSanctum  Spell
ResilientSphere  Spell
SecretChest  Spell
StoneShape  Spell
Stoneskin  Spell
WallOfFire Spell
AnimateObjects  Spell
ArcaneHand  Spell
Cloudkill  Spell
ConeOfCold  Spell
ConjureElemental  Spell
ContactOtherPlane  Spell
Creation  Spell
DominatePerson  Spell
Dream  Spell
Geas  Spell
HoldMonster  Spell
LegendLore  Spell
Mislead  Spell
ModifyMemory  Spell
Passwall  Spell
PlanarBinding  Spell
Scrying  Spell
Seeming  Spell
Telekinesis  Spell
TelepathicBond  Spell
TeleportationCircle  Spell
WallOfForce  Spell
WallOfStone Spell
ChainLightning  Spell
CircleOfDeath  Spell
Contingency  Spell
CreateUndead  Spell
Disintegrate  Spell
Eyebite  Spell
FleshToStone  Spell
FreezingSphere  Spell
GlobeOfInvulnerability  Spell
GuardsAndWards  Spell
InstantSummons  Spell
IrresistibleDance  Spell
MagicJar  Spell
MassSuggestion  Spell
MoveEarth  Spell
ProgrammedIllusion  Spell
Sunbeam  Spell
TrueSeeing  Spell
WallOfIce Spell
ArcaneSword  Spell
DelayedBlastFireball  Spell
Etherealness  Spell
FingerofDeath  Spell
Forcecage  Spell
MagnificentMansion  Spell
MirageArcane  Spell
PlaneShift  Spell
PrismaticSpray  Spell
ProjectImage  Spell
ReverseGravity  Spell
Sequester  Spell
Simulacrum  Spell
Symbol  Spell
Teleport Spell
AntimagicField  Spell
AntipathySympathy  Spell
Clone  Spell
ControlWeather  Spell
Demiplane  Spell
DominateMonster  Spell
Feeblemind  Spell
IncendiaryCloud  Spell
Maze  Spell
MindBlank  Spell
PowerWordStun  Spell
Sunburst Spell
AstralProjection  Spell
Foresight  Spell
Gate  Spell
Imprisonment  Spell
MeteorSwarm  Spell
PowerWordKill  Spell
PrismaticWall  Spell
Shapechange  Spell
TimeStop  Spell
TruePolymorph  Spell
Weird  Spell
Wish Spell


}